name: Deploy to GitHub container registry
 
on:
  pull_request:
    branches:
      # - dev
      - main
  push:
    branches:
      - "dev"

permissions:
  packages: write
  contents: read

env:
  FORCE_COLOR: 3
       
jobs:
  dev:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
            
      - name: Setup Python
        uses: actions/setup-python@v2
            
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Run test
        run: pytest test_api.py 
      
  main:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.event.pull_request.base.ref == 'main'
    needs: ['dev']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
                  
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/fast-api:v2 .
          docker push ${{ secrets.DOCKER_USERNAME }}/fast-api:v2
          
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GHCR_TOKEN}}

      - name: Build and Publish latest service image
        uses: pmorelli92/github-container-registry-build-push@2.0.0
        with:
            github-push-secret: ${{secrets.GITHUB_TOKEN}}
            docker-image-name: fastapi
            docker-image-tag: latest 
         