name: Deploy to GitHub container registry
 
on:
  pull_request:
    branches:
      - dev
      - main

jobs:
  build_tag_push_to_ghcr:
    runs-on: ubuntu-latest
    steps:
      - name: Build, Tag and Push Docker Image to GHCR
        uses: GlueOps/github-actions-build-push-containers@v0.1.3