name: CI/CD Pipeline

on:  
  pull_request:
    branches:
      - dev
      - main
      
env:
  FORCE_COLOR: 3
 
jobs:
  dev:
    runs-on: ubuntu-v1
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn

  staging:
    runs-on: ubuntu-v1
    if: github.ref == 'refs/heads/staging' || github.event.pull_request.base.ref == 'staging'
    needs: ['dev']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
    
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: Install dependencies
        run: yarn
      
      - name: Run tests
        run: yarn test --coverage

  main:
    runs-on: ubuntu-v1
    if: github.ref == 'refs/heads/main' || github.event.pull_request.base.ref == 'main'
    needs: ['dev']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: Install dependencies
        run: yarn

      -  name: Login to Docker Hub
         uses: docker/login-action@v2
         with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_TOKEN }}
            
      -   name: Build and push Docker image
          run: |
            ls -la
            docker build -t ${{ secrets.DOCKER_USERNAME }}/fast-api:v1 .
            docker push ${{ secrets.DOCKER_USERNAME }}/fast-api:v1